name: Rust Setup
description: Install Linux deps, setup Rust toolchain, and cache cargo.

inputs:
  with-clippy:
    description: Install clippy component.
    required: false
    default: "false"
  linux-packages:
    description: Space-separated Linux packages.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: step::install_linux_dependencies
      if: runner.os == 'Linux' && inputs.linux-packages != ''
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.linux-packages }}

    - name: step::setup_rust_with_clippy
      if: inputs.with-clippy == 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: step::setup_rust
      if: inputs.with-clippy != 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: step::cache_cargo
      uses: Swatinem/rust-cache@v2
