name: Check and Build

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/reusable-checks.yml

  build:
    needs: checks
    uses: ./.github/workflows/reusable-build.yml
    with:
      include_installers: false
